# Main configuration file of the menu generator.
# Paths are relative to this file (the config/ directory).
menu: ../menu/menu.yaml
menu_schema: menu_schema.yaml
data_rules: menu_data.yaml
flatten: output/flatterned.json
generation_files: files.yaml
